In [1]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Deep Neural Networks

## Text Generation with RNN

In [2]:
###-----------------
### Import Libraries
###-----------------

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from collections.abc import Callable
from typing import Literal
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, ConfusionMatrixDisplay
from sklearn.preprocessing import StandardScaler
import tensorflow as tf 

%matplotlib inline

2023-12-02 13:28:59.591539: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
# gpus = tf.config.list_physical_devices('GPU')

# try:
#     for g in gpus:
#         tf.config.experimental.set_memory_growth(g, True)
#     logical_gpus = tf.config.list_logical_devices('GPU')
#     print (len(gpus), 'Phusical GPUs', len(logical_gpus), 'Logical GPUs')
# except:
#     print ('invalid device')

In [4]:
###----------------
### Some parameters
###----------------

inpDir = '../../input'
outDir = '../output'
subDir = 'Shakespeare'
modelDir = '.../models'

RANDOM_STATE = 24 # REMEMBER: to remove at the time of promotion to production
np.random.seed(RANDOM_STATE) # Set Random Seed for reproducible  results

EPOCHS = 10 # number of epochs
ALPHA = 0.01 # learning rate
TEST_SIZE = 0.2
BATCH_SIZE = 32
TRAIN_SIZE = 256 # fix size of train set sot that we have batches of same size
PATIENCE = 10

# parameters for Matplotlib
params = {'legend.fontsize': 'x-large',
          'figure.figsize': (15, 8),
          'axes.labelsize': 'x-large',
          'axes.titlesize':'x-large',
          'xtick.labelsize':'x-large',
          'ytick.labelsize':'x-large'
         }

CMAP = 'coolwarm' # plt.cm.Spectral

plt.rcParams.update(params)

## Generate Data Set
Shakespeare Dataset

In [5]:
text = open('shakespeare.txt', 'rb').read().decode(encoding='utf-8')

len(text)

1115395

In [6]:
vocab = sorted(set(text))
len(vocab)

65

In [7]:
tf.__version__

'2.12.0'

In [8]:
#vocab

In [9]:
char2idx = {u:i for i, u in enumerate (vocab)}

#char2idx

In [10]:
idx2char = np.array(vocab)

idx2char

array(['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype='<U1')

In [11]:
text_as_int = np.array([char2idx[c] for c in text])

text_as_int.shape

(1115395,)

In [12]:
text_as_int

array([18, 47, 56, ...,  8,  0,  0])

In [13]:
text[:14]

'First Citizen:'

In [14]:
idx2char[18]

'F'

In [15]:
dataset = tf.data.Dataset.from_tensor_slices(text_as_int)

# print(list(dataset.as_numpy_iterator()))

2023-12-02 13:29:03.493191: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [16]:
seq_length = 100

example_per_epoch = len(text) // (seq_length+1)

example_per_epoch

11043

In [17]:
for i in dataset.take(10):
    print(i.numpy(), '|', idx2char[i.numpy()])

18 | F
47 | i
56 | r
57 | s
58 | t
1 |  
15 | C
47 | i
58 | t
47 | i


2023-12-02 13:29:03.968221: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int64 and shape [1115395]
	 [[{{node Placeholder/_0}}]]


In [18]:
sequence = dataset.batch(seq_length + 1 , 
                         drop_remainder=True) # convert to batch

for item in sequence.take(2):
    
    print(item)
    
    print(repr(''.join(idx2char[item.numpy()] ) ) ) #take index values and convert to char
    
    print('\n')

2023-12-02 13:29:04.165783: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int64 and shape [1115395]
	 [[{{node Placeholder/_0}}]]


tf.Tensor(
[18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43
  1 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43
 39 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49
  6  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10
  0 37 53 59  1], shape=(101,), dtype=int64)
'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou '


tf.Tensor(
[39 56 43  1 39 50 50  1 56 43 57 53 50 60 43 42  1 56 39 58 46 43 56  1
 58 53  1 42 47 43  1 58 46 39 52  1 58 53  1 44 39 51 47 57 46 12  0  0
 13 50 50 10  0 30 43 57 53 50 60 43 42  8  1 56 43 57 53 50 60 43 42  8
  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 18 47 56 57 58  6  1
 63 53 59  1 49], shape=(101,), dtype=int64)
'are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you k'




In [19]:
def fn_split_X_y (seq): # bring in sequence of length 101
    
    input_text = seq[:-1] # input is first 100 chars
    
    output_text = seq[1:] # output is first 100 chars
    
    return input_text, output_text

dataset = sequence.map(fn_split_X_y)

In [20]:
for X, y in dataset.take (2):
    print (repr(''.join(idx2char[X.numpy()] ) ) ) # X data
    print (repr(''.join(idx2char[y.numpy()] ) ) ) # y data
    print ('-'*50)

'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou'
'irst Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou '
--------------------------------------------------
'are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you '
're all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you k'
--------------------------------------------------


2023-12-02 13:29:04.621210: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int64 and shape [1115395]
	 [[{{node Placeholder/_0}}]]


In [21]:
BUFFER_SIZE = 1000

dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder = True)

In [22]:
vocab_size = len(vocab)

embedding_dim = 256

rnn_units = 1024

def build_model(vocab_size, 
                embedding_dim, 
                rnn_units, 
                batch_size = BATCH_SIZE):
    
    model = tf.keras.Sequential([
        
        tf.keras.layers.Embedding(vocab_size,
                                  embedding_dim,
                                  batch_input_shape = [batch_size, None]),
        
        tf.keras.layers.GRU(rnn_units,
                            return_sequences = True,
                            stateful = True,
                            recurrent_initializer = 'glorot_uniform'),
        
        tf.keras.layers.Dense(vocab_size)
    ])
    
    return model

model = build_model(vocab_size, 
                    embedding_dim, 
                    rnn_units)

2023-12-02 13:29:05.574376: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-12-02 13:29:05.576798: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-12-02 13:29:05.578498: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (32, None, 256)           16640     
                                                                 
 gru (GRU)                   (32, None, 1024)          3938304   
                                                                 
 dense (Dense)               (32, None, 65)            66625     
                                                                 
Total params: 4,021,569
Trainable params: 4,021,569
Non-trainable params: 0
_________________________________________________________________


In [24]:
for X, y in dataset.take(2):
    
    y_pred = model(X)

2023-12-02 13:29:05.780195: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int64 and shape [1115395]
	 [[{{node Placeholder/_0}}]]
2023-12-02 13:29:05.781139: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int64 and shape [1115395]
	 [[{{node Placeholder/_0}}]]


In [25]:
y_pred.shape

TensorShape([32, 100, 65])

In [26]:
loss_function = tf.losses.SparseCategoricalCrossentropy(from_logits= True)

In [27]:
model.compile(optimizer='adam', 
              loss=loss_function)

In [28]:
chkPtPath = os.path.join(modelDir, subDir)

chkPtPrefix = os.path.join(chkPtPath, 'chkpt_{epoch}')

checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(filepath=chkPtPrefix, save_weights_only=True)

In [29]:
history = model.fit(dataset, epochs=EPOCHS, callbacks=[checkpoint_callback])

Epoch 1/10


2023-12-02 13:29:08.445742: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int64 and shape [1115395]
	 [[{{node Placeholder/_0}}]]
2023-12-02 13:29:08.446394: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int64 and shape [1115395]
	 [[{{node Placeholder/_0}}]]
2023-12-02 13:29:08.808395: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_d

345/345 [==============================] - 1123s 3s/step - loss: 2.3198
Epoch 2/10
345/345 [==============================] - 1107s 3s/step - loss: 1.6916
Epoch 3/10
345/345 [==============================] - 1125s 3s/step - loss: 1.4993
Epoch 4/10
345/345 [==============================] - 1127s 3s/step - loss: 1.4050
Epoch 5/10
345/345 [==============================] - 1121s 3s/step - loss: 1.3450
Epoch 6/10
345/345 [==============================] - 1121s 3s/step - loss: 1.2980
Epoch 7/10
345/345 [==============================] - 1116s 3s/step - loss: 1.2560
Epoch 8/10
345/345 [==============================] - 1118s 3s/step - loss: 1.2151
Epoch 9/10
345/345 [==============================] - 1088s 3s/step - loss: 1.1778
Epoch 10/10
273/345 [======================>.......] - ETA: 3:48 - loss: 1.1394

In [ ]:
tf.train.latest_checkpoint(chkPtPath)

In [ ]:
model = build_model(vocab_size, 
                    embedding_dim, 
                    rnn_units,
                    batch_size = 1)

model.load_weights(tf.train.latest_checkpoint(chkPtPath))

model.summary()

2023-12-02 12:22:26.335077: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-12-02 12:22:26.337630: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-12-02 12:22:26.339380: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

AttributeError: 'NoneType' object has no attribute 'endswith'

In [ ]:
model.build(tf.TensorShape([1, None] ) )

In [ ]:
def gen_text(model, start_string):
    num_generate = 1000
    
    input_eval = [char2idx[c] for c in start_string] # [37, 48, 56]
    
    print(f'Input: {start_string} | {input_eval}')
    
    input_eval = tf.expand_dims(input_eval, 0)
    
    text_generated = []
    
    model.reset_states()
    for i in range (num_generate):
        
        prediction = model(input_eval)
        
        prediction = tf.squeeze(prediction, 0)
        
        predict_td = tf.random.categorical(prediction, num_samples=1)[-1,0].numpy()
        input_eval = tf.expand_dims([predict_td], 0)
        text_generated.append(idx2char[predict_td])
        
    return start_string + ''.join(text_generated)
    

In [ ]:
gen_text(model, 'ROMEO:')

NameError: name 'chart2idx' is not defined